### ISSUE TITLE
Bind app to Windows taskbar item

### ISSUE THREAD

**Issue by rpanderson** [chrisjbillington/desktop-app#1] opened 2020-05-11 02:49 UTC
The application does not 'bind' to the Windows taskbar, i.e. opening it from any shortcut (in the start-menu, on the desktop or task bar) results in a new (detached) Python window rather than a window corresponding to the application. Pinning the active window then only results in a shortcut to the Python executable.
![taskbar](https://user-images.githubusercontent.com/5637107/81519781-b5e77600-9385-11ea-9237-ed4f78303e43.gif)

**Comment by chrisjbillington** [comment] 2020-05-11 02:58
Thanks for the bug report!

Did anything you do differ from this process?

```
pip install -e . # in desktop-app dir
pip install -e . # in example dir
desktop-app install oink
```
Then running it either from the start menu or by `oink` or `oink-gui` from the terminal.

**Comment by rpanderson** [comment] 2020-05-11 03:04
Affirmative.

**Comment by chrisjbillington** [comment] 2020-05-11 03:14
Could you change `oink/__main__.py` to show what the appid is as below, and show whether it is different when running `oink` from a terminal compared to from a shortcut?

```python
import sys
import tkinter
import desktop_app
from desktop_app.shell import _ModuleConfig

desktop_app.set_process_appid('oink')

root = tkinter.Tk(className=sys.argv[0])
root.geometry("300x300")
w = tkinter.Label(root, text=_ModuleConfig.instance('oink').appid)
w.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)
root.mainloop()```

**Comment by rpanderson** [comment] 2020-05-11 03:22
They are identical (also when running `oink-gui` from a terminal).

**Comment by chrisjbillington** [comment] 2020-05-11 03:32
Damn. It's as if  the appmodel_id of the process isn't being set properly, or wasn't set properly on the shortcut at install time.

Could you follow [these instructions](https://docs.microsoft.com/en-us/windows/configuration/find-the-application-user-model-id-of-an-installed-app), or otherwise, to check the appusermodel_id of the shortcut, and confirm it a) has one and b) matches what was displayed in the app?

FWIW pinning does work for me and I thought I'd ironed out the issues! The behaviour you're seeing is basically as if desktop-app hadn't even been written...

**Comment by rpanderson** [comment] 2020-05-11 05:11
> ... check the appusermodel_id of the shortcut, and confirm it 
> a) has one and b) matches what was displayed in the app?

It matches.

```
PS C:\Users\rpanderson> get-StartApps | findstr -I oink
Oink App                                             OldMcdonald'SFarm.Oink.Python-441fa76ae261b826
```

**Comment by rpanderson** [comment] 2020-05-11 10:14
> FWIW pinning does work for me

It works on a test runner I configured using Github Actions (`rpanderson/desktop-app@windows_test`).

The artefact from a test is shown below:
![screenshot](https://user-images.githubusercontent.com/5637107/81550635-e3ebab00-93c3-11ea-9bf9-4c6eb43d5711.png)

However, [enumerating the desktop applications](https://github.com/rpanderson/desktop-app/runs/662812267?check_suite_focus=true#step:7:16) lists the application as `python`:
```
 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
     14     3.07      14.76       0.02    3472   1 notepad
     22    12.19      23.75       0.34    5316   1 ProcessTelemetry
     59    56.17      81.89       1.84    5288   1 provisioner
     23    20.20      33.13       0.36    3812   1 python
```
I haven't tried pinning the application to the taskbar yet, but I'll give it a go.

**Comment by rpanderson** [comment] 2020-05-11 12:48
Looks like it works in a virtual env created using `python -m venv` as well (on the test runner):
https://github.com/rpanderson/desktop-app/actions/runs/101437236

**Comment by chrisjbillington** [comment] 2020-05-11 15:39
That's really cool with the test runners!

> However, enumerating the desktop applications lists the application as python

I think that's expected. The process name is Python, we haven't tried to change that - it's the `AppUserModel_ID` that we're interested in.

Pretty stumped about it not working on your machine! There are only two steps required as far as I know: setting the `AppUserModel_ID` of the shortcut, and setting it on the process. We've verified the shortcut has it right, and we've verified the app knows the same ID, though we didn't do any kind of read-back to confirm it was set on the process correctly.

You could verify it by calling:

```python
from win32com.shell import shell
appid = shell.GetCurrentProcessExplicitAppUserModelID()
```

and having the example display that too.

**Comment by rpanderson** [comment] 2020-05-12 03:03
> I think that's expected. The process name is Python, we haven't tried to change that - it's the `AppUserModel_ID` that we're interested in.

Yep, And I've changed the process attributes displayed in [the test](https://github.com/rpanderson/desktop-app/runs/665596862?check_suite_focus=true#step:7:11) to include the window title.
```
  Id Name             ProcessName      MainWindowTitle
  -- ----             -----------      ---------------
1660 notepad          notepad          Untitled - Notepad
5608 ProcessTelemetry ProcessTelemetry C:\Users\RUNNER~1\AppData\Local\Temp\bin\ProcessTelemetry.exe
5524 provisioner      provisioner      Administrator: C:\actions\runner-provisioner-Windows\provisioner.exe
1064 python           python           oink-gui
```

> You could verify it by calling:
> ```python
> from win32com.shell import shell
> appid = shell.GetCurrentProcessExplicitAppUserModelID()
> ```
> and having the example display that too.

Done. They're all the same both in the successful test and in my errant local installation.

**Comment by chrisjbillington** [comment] 2020-05-12 03:49
Thanks.

I see this snippet in our old installer:

```python
    if os.name == 'nt':
        from labscript_utils.winshell import make_shortcut, add_to_start_menu
        for appname in gui_programs:
            shortcut_path = make_shortcut(appname)
            add_to_start_menu(shortcut_path)
        # Clear the icon cache so Windows gets the shortcut icons right even if they were previously broken:
        if not (struct.calcsize("P") == 8) and (platform.machine().endswith('64')):
            # 64-bit windows auto-redirects 32-bit python calls away from system32
            # have to use full path with emulator re-direct
            exe = os.path.join(os.environ['WINDIR'],'sysnative','ie4uinit.exe')
        else:
            exe = 'ie4uinit.exe'
            
        try:
            subprocess.Popen([exe, '-ClearIconCache'])
        except Exception:
            sys.stderr.write('failed to clear icon cache, icons might be blank\n')
    print('done')
```

But it sounds more like it's about the actual icons rather than the appids. Could be worth a shot though, do you wanna try running:

```
ie4uinit.exe -ClearIconCache
```

And seeing if it helps?

And maybe I should add this to `desktop-app install` even if it is just about the icons.

One more piece of data might be whether it is still broken if you do it again in a new venv (not at the same filepath as the previous venv - this will ensure the appid is different). To check if it's consistently broken on your machine or a once-off (I assume you probably tried multiple times already, but perhaps not with a different venv filepath).

Other than that I think we might just have to wait and see what proportion of systems this breaks on, since I can't see what we're doing wrong. We could switch back to more laboriously setting the appid on individual windows I guess, but I was hoping to avoid that.

**Comment by rpanderson** [comment] 2020-05-12 05:11
After circumventing some path resolution issues in #2, I see this same issue on another Windows 10 host. These hosts share the following in common:
- Managed operating environment.
- Python 3.8 from Windows Store.

**Comment by chrisjbillington** [comment] 2020-05-12 05:29
Sweet!

I'll try to reproduce with the Python from the Windows store. I haven't been able to download it because there's a bug where the download button does nothing if you decided not to link your login to a Microsoft account or something like that. But I'll figure it out.

4322167a9390d767c93784d300da553f9de3629f doesn't make a difference by any chance, does it?

Also, what filepath does the shortcut get created at?

Maybe there's a similar "per user" thing going on where the application is running with system-installed python (via a venv maybe, but task manager shows the process tree has the original Python interpreter in it), but the shortcut was installed to the user's start menu - perhaps these appids are per-user.

**Comment by rpanderson** [comment] 2020-05-12 05:51
> I haven't tried pinning the application to the taskbar yet, but I'll give it a go.

Programmatically pinning to the taskbar [isn't as easy](https://stackoverflow.com/questions/31720595/pin-program-to-taskbar-using-ps-in-windows-10) as it [used to be](https://stackoverflow.com/a/9739830). (The `Pin to Tas&kbar` and `taskbarpin` verbs are no longer present.) 

There's also [XML + Group Policy](https://docs.microsoft.com/en-us/windows/configuration/configure-windows-10-taskbar).

**Comment by rpanderson** [comment] 2020-05-12 06:11
>  do you wanna try running:
> ```
> ie4uinit.exe -ClearIconCache
> ```
> And seeing if it helps?

No dice.

> One more piece of data might be whether it is still broken if you do it again in a new venv (not at the same filepath as the previous venv - this will ensure the appid is different).

I can reproduce this on venv-created virtual environment (or in the base environment) of the Windows hosts I've been testing on.

> 4322167 doesn't make a difference by any chance, does it?
> Also, what filepath does the shortcut get created at?

Per [this comment](https://github.com/chrisjbillington/desktop-app/issues/3#issuecomment-627123284) on #3, it does not. And the shortcuts that get created are now broken on both Windows hosts I'm testing on locally. They target `%PROGRAMFILES%\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\Scripts` which doesn't exist, and should be `%LOCALAPPDATA%\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts`.

**Comment by chrisjbillington** [comment] 2020-05-12 18:59
> Programmatically pinning to the taskbar isn't as easy as it used to be.

In `labscript_utils.winshell` we were doing the following to update a pinned shortcut. It worked when I last tried it!

```python
def update_if_pinned(shortcut):
    """If a shortcut with the same name is pinned to the taskbar, delete it and replace
    it with the given shortcut"""
    basename = os.path.basename(shortcut)
    appdata = shell.SHGetFolderPath(0, shellcon.CSIDL_APPDATA, None, 0)
    taskbar_pinned_dir = os.path.join(
        appdata,
        'Microsoft',
        'Internet Explorer',
        'Quick Launch',
        'User Pinned',
        'TaskBar',
    )
    if basename in os.listdir(taskbar_pinned_dir):
        print("Updating pinned shortcut %s" % basename)
        os.unlink(os.path.join(taskbar_pinned_dir, basename))
        shutil.copy(shortcut, taskbar_pinned_dir)
```

So long as this still works, I should have `desktop-app` delete pinned versions of the shortcut upon uninstall, and overwrite them upon install (install overwrites existing shortcuts presently, printing a warning).

**Comment by chrisjbillington** [comment] 2020-05-12 22:37
I can reproduce the issue with Microsoft Store Python 3.8.

The problem may be something to do with Store Python's start menu item having an explicit AppUserModeID set already, which is not the case with Python.org Python (being just the .exe):

```powershell
PS C:\Users\bilbo> get-StartApps | findstr -I python
Python 3.8 (64-bit)                               C:\Users\bilbo\AppData\Local\Programs\Python\Python38\python.exe
Python 3.8 Module Docs (64-bit)                   Microsoft.AutoGenerated.{4D6F2B14-E427-0DCF-26E9-2CAD46A06DCD}
IDLE (Python 3.8 64-bit)                          Microsoft.AutoGenerated.{632C199A-74A0-FA77-B4FC-2BE632EE30C7}
Oink App                                          OldMcdonald'SFarm.Oink.Python-998a5d3c4b8f0e90
Python 3.8                                        PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0!Python
IDLE (Python 3.8)                                 PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0!Idle
```

Although calling `GetCurrentProcessExplicitAppUserModelID()` within the process before we set our own appid fails (implying the Python interpreter has not already set an AppUserModeID), perhaps Windows is prioritising the fact that this launcher with an AppUserModeID exists that points to the executable, over the fact that the process declares its own AppUserModeID, in determining which appid to associate it with.

I'll test whether setting the appids on individual windows is enough to convince Windows that they belong to the stated application, but that would be a bit of a pain in the neck.

**Comment by chrisjbillington** [comment] 2020-05-12 23:54
Setting the AppUserModelID of individual windows works for Qt and Store Python, but not for tkinter (doesn't work for tkinter on Python.org Python either).

So if we want it to work for us we will just need to move back to setting the appid on individual windows - will think about how to streamline this.

Pity about tkinter, but it's pretty hard to make a serious app with tkinter, it's mostly for the example.

**Comment by chrisjbillington** [comment] 2020-05-13 00:01
Haha, we may be able to automatically hook into new window creation without the user having to set anything in their particular GUI library!

With the SetWinEventHook function. I'll investigate before resigning to the per-window user code solution, which it would be really nice to avoid.

https://stackoverflow.com/questions/15849564/how-to-use-winapi-setwineventhook-in-python

**Comment by chrisjbillington** [comment] 2020-05-13 02:29
The SetWinEventHook approach is very promising! This script sucessfully identifies itself as 'oink app' running under store-bought Python, as does the Qt equivalent, as do both on Python.org Python.

One rough edge is that it's asynchronous - the window briefly identifies incorrectly before getting fixed. This can likely be fixed by setting a flag that makes the calls synchronous, though that means the callback function needs to be in a dll, which will require Cython. Might do that anyway since all this ctypes will be nicer in Cython in any case.

```python
import sys
import os
import ctypes
import ctypes.wintypes

WINEVENT_INCONTEXT = 4
WINEVENT_OUTOFCONTEXT = 0x0000
EVENT_OBJECT_CREATE = 0x8000
OBJID_WINDOW = 0x00000000

user32 = ctypes.windll.user32
ole32 = ctypes.windll.ole32

from desktop_app.shell import _ModuleConfig

appid = _ModuleConfig.instance('oink').appid


def set_appusermodel(window_id, appid):
    print(window_id, appid)
    from win32com.propsys import propsys, pscon

    store = propsys.SHGetPropertyStoreForWindow(window_id, propsys.IID_IPropertyStore)
    store.SetValue(pscon.PKEY_AppUserModel_ID, propsys.PROPVARIANTType(appid))
    store.Commit()


def callback(
    hWinEventHook, event, hwnd, idObject, idChild, dwEventThread, dwmsEventTime
):
    if idObject == OBJID_WINDOW:
        set_appusermodel(hwnd, appid)

ole32.CoInitialize(0)

WinEventProcType = ctypes.WINFUNCTYPE(
    None,
    ctypes.wintypes.HANDLE,
    ctypes.wintypes.DWORD,
    ctypes.wintypes.HWND,
    ctypes.wintypes.LONG,
    ctypes.wintypes.LONG,
    ctypes.wintypes.DWORD,
    ctypes.wintypes.DWORD,
)

WinEventProc = WinEventProcType(callback)

user32.SetWinEventHook.restype = ctypes.wintypes.HANDLE
hook = user32.SetWinEventHook(
    EVENT_OBJECT_CREATE,
    EVENT_OBJECT_CREATE,
    0,
    WinEventProc,
    os.getpid(),
    0,
    WINEVENT_OUTOFCONTEXT,
)
if hook == 0:
    print('SetWinEventHook failed')
    sys.exit(1)


import tkinter
root = tkinter.Tk(className=sys.argv[0])
root.geometry("500x300")
w = tkinter.Label(root, text="Oink!")
w.place(relx=0.5, rely=0.3, anchor=tkinter.CENTER)
sys_info = (
    f"sys.prefix: {sys.prefix}\n"
    f"sys.exec_prefix: {sys.exec_prefix}\n"
    f"sys.executable: {sys.executable}"
)
s = tkinter.Label(root, text=sys_info, justify=tkinter.LEFT)
s.place(relx=0.05, rely=0.5, anchor=tkinter.W)
root.mainloop()
```

**Comment by chrisjbillington** [comment] 2020-05-14 23:45
This is fixed via the SetWinEventHook method.

However, it requires compiling a C++ extension to work, since Windows needs you to give it a handle to the DLL the callback is in in order to make the calls synchronous.

The callbacks running synchronously doesn't just mean you avoid seeing  the window initially grouped wrongly at startup, it also means you get to unset the appid before the window is destroyed. This is apparently important to not leak the memory associated with setting window properties (one appid might not be much memory, but it's good manners, plus what if it means the icon leaks too? Don't know).

So setuptools will just build this, but you need to have the compiler on your system: https://wiki.python.org/moin/WindowsCompilers

Will have to work out how to ship wheels given that we want to compile this extension on Windows but not on Linux. If I just leave it out of setup.py with an `if` statement as at present, then I think if I build a wheel on Linux setuptools thinks it's a platform-independent wheel since there are no extensions. That's not what we want.

**Comment by rpanderson** [comment] 2020-05-15 03:49
> This is fixed via the SetWinEventHook method.

Good news!

> However, it requires compiling a C++ extension to work, since Windows needs you to give it a handle to the DLL the callback is in in order to make the calls synchronous.

How annoying. This introduces a dependency that requires administrative rights (I don't know of a compiler on Windows that doesn't require it).

It is also a remarkably heavy dependency just to create shortcuts :-(

**Comment by chrisjbillington** [comment] 2020-05-15 03:51
> How annoying. This introduces a dependency that requires administrative rights (I don't know of a compiler on Windows that doesn't require it).

Interesting. In any case, we'll ship pre-built wheels so it won't matter. I can put one up right now if you're interested in testing

**Comment by rpanderson** [comment] 2020-05-15 03:53
>  In any case, we'll ship pre-built wheels so it won't matter.

Yep, it means that you'll be restricted to a built distribution, i.e. non-editable on Windows without admin rights. So be it.

>  I can put one up right now if you're interested in testing

Fire away.

**Comment by chrisjbillington** [comment] 2020-05-15 04:05
> Yep, it means that you'll be restricted to a built distribution, i.e. non-editable on Windows without admin rights. So be it.

Hopefully we can nail this package relatively firmly down so it doesn't need hacking on too regularly. Runviewer has an extension too that it would be more kosher for us to not include in the repository precompiled. Perhaps there's a way to circumvent rebuilding if you're not hacking on the extension itself - I mean the precompiled extension is there on PyPI, you just gotta get it into your project.

> Fire away

Whoops, put it real PyPI (dev version though so shouldn't be default):

https://pypi.org/project/desktop-app/0.1.1.dev5/

Py38 64 bit Windows only. I thought I set the settings to be ABI compatible with all recent Pythons, but the wheel doesn't reflect that for some reason, so 3.8 only for now. I'll figure that out later.

**Comment by rpanderson** [comment] 2020-05-15 05:50
Works with 0.1.1dev5 and the example app both installed via pip.

When trying to install the example app with:
```
python setup.py install
```
I got:
```
C:\Users\rpanderson\src\example>python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-11292.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\Lib\site-packages\
```
... and obviously needed a `--user` install. Trying this, i.e. `python setup.py install --user` gets `oink` installed, but `desktop-app install oink` then failed with:
```python-traceback
Traceback (most recent call last):
  File "C:\Users\rpanderson\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\desktop-app-script.py", line 11, in <module>
    load_entry_point('desktop-app==0.1.1.dev5', 'console_scripts', 'desktop-app')()
  File "C:\Users\rpanderson\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\desktop_app\__main__.py", line 42, in main
    install(args.module, path=args.path, verbose=not args.quiet)
  File "C:\Users\rpanderson\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\desktop_app\shell.py", line 219, in install
    raise EnvironmentError(' '.join(msg.split()))
OSError: The package providing the module oink is not installed to the current Python environment, so its entry_points scripts do not exist, and desktop-app cannot create shortcuts to them. Install the package to the Python environment before continuing. If you are in a development setup you may make an editable install with `pip install -e`.
```
Reinstalling the example app with pip worked just fine, though.
```
pip install example
desktop-app install oink
```

**Comment by chrisjbillington** [comment] 2020-05-15 15:04
Thanks, fixed in 4fba806e422d52da3dd0a2188ee5a73084d88d5d.

Problem was that `python setup.py install` installs en `.egg` directory, meaning the import path is nested a little bit below site-packages, rather than being directly in it. I've now accounted for that by looking for site-packages as a parent directory of the found import path, rather than an exact match to its immediate parent.

However, I couldn't run `desktop-app install` after installing `desktop-app` with `--user`, because the Scripts directory for `--user`-installed packages was not in my `PATH`. Which is a common problem for `--user` installed packages, even on Linux where the official standards (which are nothing to do with Python) say that it should be. It's a frustrating ongoing problem.

So I had to run `python -m desktop_app install` instead.

Did you explicitly add `'C:\\Users\\rpanderson\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\Scripts'` to your PATH by any chance?

**Comment by rpanderson** [comment] 2020-05-16 00:09
> Thanks, fixed in [4fba806](https://github.com/chrisjbillington/desktop-app/commit/4fba806e422d52da3dd0a2188ee5a73084d88d5d).

Cool. I can't test this on the host in question without a built distribution.

> Did you explicitly add `'C:\\Users\\rpanderson\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\Scripts'` to your PATH by any chance?

Nope, it was already there.

**Comment by chrisjbillington** [comment] 2020-05-16 00:24
> Nope, it was already there.

Huh, looks like it's there for me too now - maybe I just needed to reboot.

> Cool. I can't test this on the host in question without a built distribution.

Done:
```
pip install --index-url https://test.pypi.org/simple desktop-app==0.1.1.dev6
```

**Comment by rpanderson** [comment] 2020-05-16 01:03
0.1.1.dev6 resolves the `python setup.py install` issue above for me on a non-admin accout using Windows Store Python.

**Comment by chrisjbillington** [comment] 2020-05-16 02:15
Thanks for testing!

Closing as all issues raised in this thread are fixed

**Closed as completed by chrisjbillington** 2020-05-16 02:15 UTC
